### PR TITLE
Chores/base64 bug

### LINKED ISSUE #29: Fix Bug where the images arent parsing to base 64 string

### PR DESCRIPTION
**Pull request by BlueNealis**
<h1>PULL REQUEST</h1>

<ul>
  <li>What does it change?</li>
   - Removes unecessary packages relating to base64
   - Adds base64 functionality to our image picker functions
  <li>What does it fix?</li>
 - Means we can upload and send requests via our phones. 

</ul>

<h2>Type of Change</h2>

_Delete options that are not relevant_

- [x] **Bug Fix**

<h2>How has this been tested?</h2>

- [x] **JS**
- [ ] **Dev Tools**
- [x] **Website**

<h2>Checklist</h2>

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new bugs
- [x] I have tagged project partners for review & it has been reviewed 

Other Concerns for Teammates

- Error handling needs to be added so that the code doesnt break if the api doesnt send an image in the response.  At the moment sometimes when you send an image in if the plant that returns doesnt have that information it breaks the response page. 

<h2>Does this PR close any issues?</h2>
close #29

### CODE REVIEW

**Review by ameliaeiger — APPROVED** [review]

**Review by Neil-B-Linton — APPROVED** [review]
Wow...  so surprised that it was just something through image picker.. So awesome we found a fix for this.

File: App.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import Results from './components/Results';
 import {NavigationContainer} from "@react-navigation/native"
 import { createNativeStackNavigator } from '@react-navigation/native-stack';
 import {API_KEY} from "./API_KEY.js"
-
+import imageToBase64 from 'image-to-base64/browser'
```
Comment (laytonmaes) [inline App.js]: this is not needed anymore

**Review by laytonmaes — APPROVED** [review]
